#include "veloxa/api/veloxa_api.h"

// Generated by CMake configure_file from veloxa/api/version.h.in.
// Provides VELOXA_VERSION_STRING — synced with project(VERSION ...) in root
// CMakeLists.txt. Do not hardcode version literal in this file.
#include "veloxa/api/version.h"

#include <cstring>

#include "veloxa/core/application.h"
#include "veloxa/platform/event_loop.h"
#include "veloxa/platform/headless/headless_event_loop.h"
#include "veloxa/platform/headless/memory_surface.h"
#include "veloxa/platform/surface.h"

#ifdef VX_PLATFORM_SDL2
#include "veloxa/platform/sdl2/sdl2_event_loop.h"
#include "veloxa/platform/sdl2/sdl2_window_surface.h"
#endif

#ifdef VX_BUILD_DEVTOOL
#include "veloxa/core/dom/serializer.h"
#include "veloxa/devtool/hot_reload/hot_reload_manager.h"
#include "veloxa/devtool/inspector/inspector_data.h"
#endif

static vx::event::EventType MapEventType(VxEventType type) {
  switch (type) {
    case VX_EVENT_POINTER_MOVE:
      return vx::event::EventType::kPointerMove;
    case VX_EVENT_POINTER_DOWN:
      return vx::event::EventType::kPointerDown;
    case VX_EVENT_POINTER_UP:
      return vx::event::EventType::kPointerUp;
    case VX_EVENT_KEY_DOWN:
      return vx::event::EventType::kKeyDown;
    case VX_EVENT_KEY_UP:
      return vx::event::EventType::kKeyUp;
    default:
      return vx::event::EventType::kPointerMove;
  }
}

static vx::gfx::Color ColorFromRGBA(uint32_t rgba) {
  return vx::gfx::Color::FromRGBA(
      static_cast<vx::u8>((rgba >> 24) & 0xFF),
      static_cast<vx::u8>((rgba >> 16) & 0xFF),
      static_cast<vx::u8>((rgba >> 8) & 0xFF),
      static_cast<vx::u8>(rgba & 0xFF));
}

extern "C" {

/* ── Event Loop ─────────────────────────────────────────────────── */

VxEventLoop* vx_event_loop_create_headless(void) {
  auto* loop = new vx::platform::HeadlessEventLoop();
  return reinterpret_cast<VxEventLoop*>(loop);
}

VxEventLoop* vx_event_loop_create_sdl2(void) {
#ifdef VX_PLATFORM_SDL2
  auto* loop = new vx::platform::Sdl2EventLoop();
  return reinterpret_cast<VxEventLoop*>(loop);
#else
  return nullptr;
#endif
}

VxResult vx_event_loop_pump_input(VxEventLoop* loop, VxView* view) {
  if (!loop || !view) return VX_ERROR_NULL_PARAM;
#ifdef VX_PLATFORM_SDL2
  auto* base = reinterpret_cast<vx::platform::EventLoop*>(loop);
  auto* sdl = dynamic_cast<vx::platform::Sdl2EventLoop*>(base);
  if (!sdl) return VX_ERROR_INVALID_STATE;
  // Bind callback on every call (cheap; lets caller swap views per frame).
  sdl->SetInputCallback([view](const VxInputEvent& e) {
    vx_view_inject_input(view, &e);
  });
  sdl->PumpInputEvents();
  return VX_OK;
#else
  (void)loop; (void)view;
  return VX_ERROR_INVALID_STATE;
#endif
}

void vx_event_loop_destroy(VxEventLoop* loop) {
  // ABI contract: handle is always a vx::platform::EventLoop* (or derived);
  // base class has virtual ~. Adding multiply-inherited backends would break
  // this reinterpret_cast — see TASK-20260425-01 spec §5.3.
  delete reinterpret_cast<vx::platform::EventLoop*>(loop);
}

/* ── Surface ────────────────────────────────────────────────────── */

VxSurface* vx_surface_create_memory(uint32_t width, uint32_t height) {
  auto* surface = new vx::platform::MemorySurface(width, height);
  return reinterpret_cast<VxSurface*>(surface);
}

VxSurface* vx_surface_create_window(const VxWindowOptions* opts) {
  if (!opts) return nullptr;
#ifdef VX_PLATFORM_SDL2
  auto* surface = new vx::platform::Sdl2WindowSurface(
      opts->width, opts->height, opts->title);
  if (!surface->valid()) {
    delete surface;
    return nullptr;
  }
  return reinterpret_cast<VxSurface*>(surface);
#else
  return nullptr;
#endif
}

void vx_surface_destroy(VxSurface* surface) {
  // ABI contract: handle is always a vx::platform::Surface* (or derived);
  // base class has virtual ~. Adding multiply-inherited backends would break
  // this reinterpret_cast — see TASK-20260425-01 spec §5.3.
  delete reinterpret_cast<vx::platform::Surface*>(surface);
}

VxResult vx_surface_save_ppm(const VxSurface* surface, const char* path) {
  if (!surface || !path) return VX_ERROR_NULL_PARAM;
  auto* s = reinterpret_cast<const vx::platform::Surface*>(surface);
  auto status = s->SavePPM(path);
  return status.ok() ? VX_OK : VX_ERROR_INVALID_STATE;
}

/* ── View ───────────────────────────────────────────────────────── */

VxView* vx_view_create(const VxViewConfig* config) {
  if (!config) return nullptr;

  vx::Application::Config cfg;
  cfg.event_loop =
      reinterpret_cast<vx::platform::EventLoop*>(config->event_loop);
  cfg.surface = reinterpret_cast<vx::platform::Surface*>(config->surface);
  cfg.target_fps = config->target_fps > 0 ? config->target_fps : 60;
  if (config->background_color != 0) {
    cfg.background_color = ColorFromRGBA(config->background_color);
  }

  auto* app = new vx::Application(cfg);
  return reinterpret_cast<VxView*>(app);
}

void vx_view_destroy(VxView* view) {
  delete reinterpret_cast<vx::Application*>(view);
}

VxResult vx_view_load_html(VxView* view, const char* html, uint32_t len) {
  if (!view || !html) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  app->LoadHTML(vx::StringView(html, len));
  return VX_OK;
}

VxResult vx_view_load_css(VxView* view, const char* css, uint32_t len) {
  if (!view || !css) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  app->LoadCSS(vx::StringView(css, len));
  return VX_OK;
}

VxResult vx_view_inject_input(VxView* view, const VxInputEvent* event) {
  if (!view || !event) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  vx::event::InputEvent input{};
  input.type = MapEventType(event->type);
  input.x = event->x;
  input.y = event->y;
  input.button = event->button;
  input.key_code = event->key_code;
  input.modifiers = event->modifiers;
  app->InjectInput(input);
  return VX_OK;
}

VxResult vx_view_load_font(VxView* view, const char* path,
                           const char* family) {
  if (!view || !path || !family) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  auto status =
      app->LoadFont(vx::StringView(path), vx::StringView(family));
  return status.ok() ? VX_OK : VX_ERROR_INVALID_STATE;
}

VxResult vx_view_load_script(VxView* view, const char* source, uint32_t len) {
  if (!view || !source) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  auto status =
      app->LoadScript(vx::StringView(source, static_cast<vx::usize>(len)));
  return status.ok() ? VX_OK : VX_ERROR_INVALID_STATE;
}

VxResult vx_view_update(VxView* view) {
  if (!view) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  app->Update();
  return VX_OK;
}

VxResult vx_view_run(VxView* view) {
  if (!view) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
#ifdef VX_PLATFORM_SDL2
  // Auto-wire SDL input forwarding when the configured event loop is the
  // SDL2 backend. Headless loops are unaffected.
  if (auto* sdl = dynamic_cast<vx::platform::Sdl2EventLoop*>(app->event_loop())) {
    sdl->SetInputCallback([view](const VxInputEvent& e) {
      vx_view_inject_input(view, &e);
    });
  }
#endif
  app->Run();
  return VX_OK;
}

VxResult vx_view_quit(VxView* view) {
  if (!view) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  app->Quit();
  return VX_OK;
}

/* ── DevTool C API thin wrapper (TASK-20260502-01 A.0.6) ────────── */

VxResult vx_view_serialize_dom_json(VxView* view, char* out_buf,
                                    uint32_t* out_len, uint32_t max_size) {
  if (!view || !out_len) return VX_ERROR_NULL_PARAM;
#ifndef VX_BUILD_DEVTOOL
  /* A14 acceptance: when DevTool is not built, the wrapper returns
   * VX_ERROR_INVALID_STATE without touching any DevTool code path so the
   * binary contains zero DevTool bytes. */
  (void)out_buf;
  (void)max_size;
  return VX_ERROR_INVALID_STATE;
#else
  auto* app = reinterpret_cast<vx::Application*>(view);
  const auto* doc = app->target_document();
  if (!doc) {
    *out_len = 0;
    return VX_OK;
  }

  /* A.2.1: policy comes from per-view state (default kRedactSensitive,
   * embedder may flip via vx_inspector_set_redaction_policy). */
  vx::String json =
      vx::devtool::SerializeDocument(doc, app->redaction_policy());
  const uint32_t needed = static_cast<uint32_t>(json.size());

  /* T7: max_size is the platform-policy hard cap. Refuse before any caller
   * allocation can happen. Boundary inclusive: needed == max_size accepts. */
  if (needed > max_size) {
    return VX_ERROR_OUT_OF_MEMORY;
  }

  /* Double-call protocol: NULL out_buf → just return required size. */
  if (!out_buf) {
    *out_len = needed;
    return VX_OK;
  }

  /* T7: caller buffer too small → refuse, do not write. */
  if (*out_len < needed) {
    return VX_ERROR_OUT_OF_MEMORY;
  }

  std::memcpy(out_buf, json.data(), needed);
  *out_len = needed;
  return VX_OK;
#endif
}

/* ── DevTool Attach C API (TASK-20260502-01 A.1.7) ────────────────
 * Thin wrapper around Application::LoadDevtoolDocument /
 * UnloadDevtoolDocument + F12 hotkey toggle. OFF path returns
 * VX_ERROR_INVALID_STATE (A14 zero-byte stub guard). */

VxResult vx_view_attach_devtool(VxView* view, const VxDevtoolOptions* opts) {
  if (!view) return VX_ERROR_NULL_PARAM;
#ifndef VX_BUILD_DEVTOOL
  (void)opts;
  return VX_ERROR_INVALID_STATE;
#else
  auto* app = reinterpret_cast<vx::Application*>(view);

  /* Defaults when caller passes NULL opts (matches A.1.7 plan contract). */
  uint32_t width = 270;
  uint8_t hotkey = 1;
  const char* hot_reload_dir = nullptr;
  if (opts) {
    width = opts->devtool_width != 0 ? opts->devtool_width : 270;
    hotkey = opts->enable_f12_hotkey;
    hot_reload_dir = opts->hot_reload_dir;
  }

  /* Clamp to documented range [200, 400] silently. */
  if (width < 200) width = 200;
  if (width > 400) width = 400;

  /* Update hotkey state BEFORE Load — Load is what actually publishes
   * the DevTool Document; hotkey enables future F12 toggles. */
  app->SetDevtoolHotkey(hotkey != 0, static_cast<vx::f32>(width));
  if (!app->LoadDevtoolDocument(static_cast<vx::f32>(width))) {
    /* canvas-missing or other failure path */
    return VX_ERROR_INVALID_STATE;
  }

  /* C.4.1 — best-effort Hot Reload attach (lazy-attach C ABI 容错 pattern,
   * Phase B B.0.1 範式 reuse). Inspector + Overlay are already published
   * above; failure here returns VX_WARNING_HOT_RELOAD_FAILED but does
   * NOT roll back the devtool_loaded() == 1 state. NULL or "" disables
   * the watcher entirely (informational, no error). */
  if (hot_reload_dir != nullptr && hot_reload_dir[0] != '\0') {
    auto* mgr = app->hot_reload_manager();
    if (mgr != nullptr) {
      auto st = mgr->Attach(vx::StringView(hot_reload_dir));
      if (!st.ok()) {
        return VX_WARNING_HOT_RELOAD_FAILED;
      }
    }
  }
  return VX_OK;
#endif
}

VxResult vx_view_detach_devtool(VxView* view) {
  if (!view) return VX_ERROR_NULL_PARAM;
#ifndef VX_BUILD_DEVTOOL
  return VX_ERROR_INVALID_STATE;
#else
  auto* app = reinterpret_cast<vx::Application*>(view);
  app->UnloadDevtoolDocument();
  /* Disable hotkey so subsequent F12 events don't auto-reattach
   * (preserves "F12 only after explicit attach" plan contract). */
  app->SetDevtoolHotkey(false);
  return VX_OK;
#endif
}

int vx_view_devtool_loaded(VxView* view) {
  if (!view) return -1;
#ifndef VX_BUILD_DEVTOOL
  return 0;
#else
  auto* app = reinterpret_cast<vx::Application*>(view);
  return app->devtool_loaded() ? 1 : 0;
#endif
}

int vx_view_hot_reload_tracked_count(VxView* view) {
  if (!view) return -1;
#ifndef VX_BUILD_DEVTOOL
  return -1;
#else
  auto* app = reinterpret_cast<vx::Application*>(view);
  auto* mgr = app->hot_reload_manager();
  if (mgr == nullptr) return 0;
  /* tracked_count() is usize; cast to signed int is safe in practice
   * (CSS hot reload tracking is bounded by user edits over a session,
   * not adversarial). Saturate negative on overflow defensively. */
  vx::usize n = mgr->tracked_count();
  if (n > static_cast<vx::usize>(INT32_MAX)) return INT32_MAX;
  return static_cast<int>(n);
#endif
}

int vx_view_is_hud_visible(VxView* view) {
  if (!view) return -1;
#ifndef VX_BUILD_DEVTOOL
  return 0;
#else
  auto* app = reinterpret_cast<vx::Application*>(view);
  return app->hud_visible() ? 1 : 0;
#endif
}

/* ── DevTool Redaction Policy (TASK-20260502-01 A.2.1, T3) ──────── */

VxResult vx_inspector_set_redaction_policy(VxView* view,
                                           VxRedactionPolicy policy) {
  if (!view) return VX_ERROR_NULL_PARAM;
#ifndef VX_BUILD_DEVTOOL
  (void)policy;
  return VX_ERROR_INVALID_STATE;
#else
  vx::dom::RedactionPolicy mapped;
  switch (policy) {
    case VX_REDACTION_REDACT_SENSITIVE:
      mapped = vx::dom::RedactionPolicy::kRedactSensitive;
      break;
    case VX_REDACTION_NONE:
      mapped = vx::dom::RedactionPolicy::kNone;
      break;
    default:
      /* Reject unknown enum values so a zero-init memory bug or future
       * enum extension cannot silently disable redaction. */
      return VX_ERROR_INVALID_STATE;
  }
  auto* app = reinterpret_cast<vx::Application*>(view);
  app->set_redaction_policy(mapped);
  return VX_OK;
#endif
}

/* ── Pipeline Hooks (TASK-20260502-02 B.0.1, #35 phase 1 closure) ── */

VxResult vx_view_set_pipeline_hooks(VxView* view,
                                    const VxPipelineHooks* hooks,
                                    void* userdata) {
  if (!view) return VX_ERROR_NULL_PARAM;
  auto* app = reinterpret_cast<vx::Application*>(view);
  /* Public ABI is intentionally available regardless of VX_BUILD_DEVTOOL —
   * profiler / tracing embedders may install hooks without DevTool. The
   * vx_devtool subsystem (B.1.x PerfOverlay) installs its own hooks via
   * the C++ Application::SetPipelineHooks API directly when DEVTOOL=ON. */
  if (!hooks) {
    bool ok = app->SetPipelineHooks(nullptr);
    return ok ? VX_OK : VX_ERROR_INVALID_STATE;
  }
  vx::PipelineHooks cpp_hooks;
  cpp_hooks.on_frame_start  = hooks->on_frame_start;
  cpp_hooks.on_after_style  = hooks->on_after_style;
  cpp_hooks.on_after_layout = hooks->on_after_layout;
  cpp_hooks.on_after_render = hooks->on_after_render;
  cpp_hooks.on_frame_end    = hooks->on_frame_end;
  cpp_hooks.userdata        = userdata;
  bool ok = app->SetPipelineHooks(&cpp_hooks);
  /* Hooks are cached even when ok=false (lazy attached on next
   * EnsureUpdateManager) — but we still return INVALID_STATE so the
   * caller knows update_manager_ wasn't ready and can either call
   * vx_view_update first or rely on the lazy attach. */
  return ok ? VX_OK : VX_ERROR_INVALID_STATE;
}

/* ── Info ───────────────────────────────────────────────────────── */

const char* vx_version(void) { return VELOXA_VERSION_STRING; }

}  /* extern "C" */
