#!/usr/bin/env python3
"""TASK-20260502-01 A.1.2: Codegen for DevTool UI resource embedding.

Reads N input files and writes a single .cc with one
`const char* const NAME = "...";` declaration per pair.

Uses Python's `json.dumps()` for string escaping — guarantees all printable
chars + control chars + non-ASCII bytes are safely embedded as a valid C++
string literal (RFC 8259 §7 escape rules are a strict subset of C++ string
literal escapes for these characters).

Invoked via CMake `add_custom_command` in
veloxa/devtool/resources/CMakeLists.txt. Output is treated as a generated
source for the vx_devtool_resources STATIC library.
"""

import argparse
import json
import sys


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--inputs", nargs="+", required=True,
                    help="Input resource files to embed.")
    ap.add_argument("--names", nargs="+", required=True,
                    help="Symbol name for each input (same length as --inputs).")
    ap.add_argument("--output", required=True,
                    help="Output .cc file.")
    args = ap.parse_args()

    if len(args.inputs) != len(args.names):
        print(f"ERROR: --inputs ({len(args.inputs)}) and --names "
              f"({len(args.names)}) must have the same length.",
              file=sys.stderr)
        return 1

    with open(args.output, "w", encoding="utf-8") as out:
        out.write('// Auto-generated by veloxa/devtool/resources/'
                  'embed_resources.py — DO NOT EDIT.\n')
        out.write('// Source files: ' + ", ".join(args.inputs) + "\n\n")
        out.write('#include "veloxa/devtool/resources/'
                  'inspector_resources.h"\n\n')
        out.write("namespace vx::devtool::resources {\n\n")
        for path, name in zip(args.inputs, args.names):
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            # json.dumps gives a valid C++ string literal for all UTF-8
            # text resources (no embedded NUL bytes).
            escaped = json.dumps(content)
            out.write(f"const char* const {name} = {escaped};\n\n")
        out.write("}  // namespace vx::devtool::resources\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
